[package]
name = "othello"
version = "0.1.0"
authors = ["Arne Dussin <arne.dussin@live.de>"]

[[bin]]
name = "server"
path = "src/server.rs"

[[bin]]
name = "client"
path = "src/client.rs"

[dependencies]
sfml = "*"
bincode = "*"
lazy_static = "*"
serde = "*"
serde_derive = "*"
toml = "*"
