[network]
server_ip = "localhost"
server_port = 44942
login_name = "John Doe"

[graphics]
board = "data/board_test.png"
# square_size = 64
white_piece = "data/white_piece_test.png"
black_piece = "data/black_piece_test.png"
shadow = "data/shadow_test.png"
white_score_colour = [244, 244, 244]
black_score_colour = [0, 0, 0]
